apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: ecommerce
spec:
  selector:
    app: cart
  ports:
    - name: http
      port: 4002
      targetPort: 4002
  type: ClusterIP

